DROP DATABASE evergreen;

CREATE DATABASE evergreen;

USE evergreen;


CREATE TABLE products (
id INT NOT NULL PRIMARY KEY,
title VARCHAR(255),
image VARCHAR(255),
alt_img VARCHAR(255),
price INT,
category VARCHAR(255),
prod_desc TEXT,
featured BOOLEAN
);

INSERT INTO products 
(id, title, image, alt_img, price, category, prod_desc, featured) VALUES
(0, "BC-Racing BR Series - e36 Sedan", "./images/prod-imgs/BC-Racinig-Coilover-Prod.png", "./images/prod-imgs/BC-Alt-Image.png", 1400, "Suspension", "The BC Racing BR Series offers the most affordable entry into coilover suspension without sacrificing performance, comfort, build quality, vehicle height, or handling. This is done by extensively testing each vehicle then refining the coilover characteristics as many times as needed to ensure the most well-balanced and affordable aftermarket suspension conceivable.", true),
(1, "BC-Racing BR Series - e46 Sedan", "./images/prod-imgs/BC-Racinig-Coilover-Prod.png", "./images/prod-imgs/BC-Alt-Image.png", 1400, "Suspension", "The BC Racing BR Series offers the most affordable entry into coilover suspension without sacrificing performance, comfort, build quality, vehicle height, or handling. This is done by extensively testing each vehicle then refining the coilover characteristics as many times as needed to ensure the most well-balanced and affordable aftermarket suspension conceivable.", false),
(2, "BC-Racing BR Series - e36 Coupe", "./images/prod-imgs/BC-Racinig-Coilover-Prod.png", "./images/prod-imgs/BC-Alt-Image.png", 1400, "Suspension", "The BC Racing BR Series offers the most affordable entry into coilover suspension without sacrificing performance, comfort, build quality, vehicle height, or handling. This is done by extensively testing each vehicle then refining the coilover characteristics as many times as needed to ensure the most well-balanced and affordable aftermarket suspension conceivable.", false),
(3, "BC-Racing BR Series - e46 Coupe", "./images/prod-imgs/BC-Racinig-Coilover-Prod.png", "./images/prod-imgs/BC-Alt-Image.png", 1400, "Suspension", "The BC Racing BR Series offers the most affordable entry into coilover suspension without sacrificing performance, comfort, build quality, vehicle height, or handling. This is done by extensively testing each vehicle then refining the coilover characteristics as many times as needed to ensure the most well-balanced and affordable aftermarket suspension conceivable.", false),
(4, "BC-Racing BR Series - NA Miata", "./images/prod-imgs/BC-Racinig-Coilover-Prod.png", "./images/prod-imgs/BC-Alt-Image.png", 1400, "Suspension", "The BC Racing BR Series offers the most affordable entry into coilover suspension without sacrificing performance, comfort, build quality, vehicle height, or handling. This is done by extensively testing each vehicle then refining the coilover characteristics as many times as needed to ensure the most well-balanced and affordable aftermarket suspension conceivable.", false),
(5, "BC-Racing BR Series - e90 Sedan", "./images/prod-imgs/BC-Racinig-Coilover-Prod.png", "./images/prod-imgs/BC-Alt-Image.png", 1400, "Suspension", "The BC Racing BR Series offers the most affordable entry into coilover suspension without sacrificing performance, comfort, build quality, vehicle height, or handling. This is done by extensively testing each vehicle then refining the coilover characteristics as many times as needed to ensure the most well-balanced and affordable aftermarket suspension conceivable.", false),
(6, "BC-Racing BR Series - s13 240sx", "./images/prod-imgs/BC-Racinig-Coilover-Prod.png", "./images/prod-imgs/BC-Alt-Image.png", 1400, "Suspension", "The BC Racing BR Series offers the most affordable entry into coilover suspension without sacrificing performance, comfort, build quality, vehicle height, or handling. This is done by extensively testing each vehicle then refining the coilover characteristics as many times as needed to ensure the most well-balanced and affordable aftermarket suspension conceivable.", false),
(7, "BC-Racing BR Series - s14 240sx", "./images/prod-imgs/BC-Racinig-Coilover-Prod.png", "./images/prod-imgs/BC-Alt-Image.png", 1400, "Suspension", "The BC Racing BR Series offers the most affordable entry into coilover suspension without sacrificing performance, comfort, build quality, vehicle height, or handling. This is done by extensively testing each vehicle then refining the coilover characteristics as many times as needed to ensure the most well-balanced and affordable aftermarket suspension conceivable.", false),
(8, "Work Emotion CR2P", "./images/prod-imgs/Work-CR2P.png", "./images/prod-imgs/Work-CR2P-Alt.png", 500, "Wheels", "Wheel Construction: 2 Piece Reverse Step Rim (17 SR / 19 SR / 20 SR, 2 Piece Full Reverse (16 / 18 / 19)", true),
(9, "Work Emotion CR3P", "./images/prod-imgs/Work-CR3P.png", "./images/prod-imgs/Work-CR3P-Alt.png", 700, "Wheels", "Wheel Construction: 3 Piece Reverse Step Rim (19 / 20 SR, 3 Piece Full Reverse (16 / 18 / 19)",false),
(10, "Work Lanvec LD1", "./images/prod-imgs/Work-LD1.png", "./images/prod-imgs/Work-LD1-Alt.png", 700, "Wheels", "Wheel Construction: 2 Piece Full Reverse (18 / 19 / 20)", false),
(11, "Work Meister S12P", "./images/prod-imgs/Work-S12P.png", "./images/prod-imgs/Work-S12P-Alt.png", 500, "Wheels", "Wheel Construction: 2 Piece Normal. Size range 15×5.5~15×10.0", false),
(12, "Work Meister S13P", "./images/prod-imgs/Work-S13P.png", "./images/prod-imgs/Work-S13P-Alt.png", 700, "Wheels", "Wheel Construction: 3 Piece Normal. Size range 18×8.0~18×16.0 / 19×8.0~19×16.0", true),
(13, "Work VS-XX", "./images/prod-imgs/Work-VS-XX-LGS.png", "./images/prod-imgs/Work-VS-XX-Alt.png", 700, "Wheels", "Wheel Construction: 3 Piece Reverse Step Rim (19SR / 20SR), 3 Piece Full Reverse (18 / 19)", false),
(14, "NRG Prisma Pizza", "./images/prod-imgs/NRG-Prisma-Pizza.png", "./images/prod-imgs/NRG-Prisma-Pizza-Alt.png", 425, "Seats", "The Prisma offers unmatched style, comfort, and innovation with things like our double layer FRP, 5-point harness compatibility, and purple flakes color backing. Wrapped in vegan satin material and insulated with hand-picked mixed-density foam while rocking two storage pockets located on the front seat cushions, it's also the first seat to retain factory like utility and support, and at a surprisingly affordable price.", false),
(15, "NRG Prisma Purple", "./images/prod-imgs/NRG-Prisma-Purple.png", "./images/prod-imgs/NRG-Prisma-Purple-Alt.png", 425, "Seats", "The Prisma offers unmatched style, comfort, and innovation with things like our double layer FRP, 5-point harness compatibility, and purple flakes color backing. Wrapped in vegan satin material and insulated with hand-picked mixed-density foam while rocking two storage pockets located on the front seat cushions, it's also the first seat to retain factory like utility and support, and at a surprisingly affordable price.", false),
(16, "NRG Prisma Sakura", "./images/prod-imgs/NRG-Prisma-Sakura.png", "./images/prod-imgs/NRG-Prisma-Sakura-Alt.png", 425, "Seats", "The Prisma offers unmatched style, comfort, and innovation with things like our double layer FRP, 5-point harness compatibility, and purple flakes color backing. Wrapped in vegan satin material and insulated with hand-picked mixed-density foam while rocking two storage pockets located on the front seat cushions, it's also the first seat to retain factory like utility and support, and at a surprisingly affordable price.", false),
(17, "NRG Prisma Savage", "./images/prod-imgs/NRG-Prisma-Savage.png", "./images/prod-imgs/NRG-Prisma-Savage-Alt.png", 425, "Seats", "The Prisma offers unmatched style, comfort, and innovation with things like our double layer FRP, 5-point harness compatibility, and purple flakes color backing. Wrapped in vegan satin material and insulated with hand-picked mixed-density foam while rocking two storage pockets located on the front seat cushions, it's also the first seat to retain factory like utility and support, and at a surprisingly affordable price.", true),
(18, "NRG Prisma Ultra", "./images/prod-imgs/NRG-Prisma-Ultra.png", "./images/prod-imgs/NRG-Prisma-Ultra-Alt.png", 425, "Seats", "The Prisma offers unmatched style, comfort, and innovation with things like our double layer FRP, 5-point harness compatibility, and purple flakes color backing. Wrapped in vegan satin material and insulated with hand-picked mixed-density foam while rocking two storage pockets located on the front seat cushions, it's also the first seat to retain factory like utility and support, and at a surprisingly affordable price.", false),
(19, "EGM OG Box Slap", "./images/home-imgs/EGM-Box-Logo2.png", "./images/home-imgs/EGM-Box-Logo2.png", 5, "Stickers", "Put them on your drift car, put them on your show car, put them on your dog(don't actually put them on your dog). It doesn't matter where you put them because purchasing one of these johnnies is about the coolest thing you could do. -- Love, the EGM Team", false),
(20, "EGM Gold Sparkle Box Slap", "./images/home-imgs/EGM-Box-Logo-Gold.png", "./images/home-imgs/EGM-Box-Logo-Gold.png", 5, "Stickers","Put them on your drift car, put them on your show car, put them on your dog(don't actually put them on your dog). It doesn't matter where you put them because purchasing one of these johnnies is about the coolest thing you could do. -- Love, the EGM Team", false),
(21, "EGM 90's Racing Box Slap", "./images/home-imgs/EGM-Box-Logo-HKS.png", "./images/home-imgs/EGM-Box-Logo-HKS.png", 5, "Stickers","Put them on your drift car, put them on your show car, put them on your dog(don't actually put them on your dog). It doesn't matter where you put them because purchasing one of these johnnies is about the coolest thing you could do. -- Love, the EGM Team", false),
(22, "EGM Logo Slap", "./images/home-imgs/EGM-Logo-Slap.png", "./images/home-imgs/EGM-Logo-Slap.png", 5, "Stickers","Put them on your drift car, put them on your show car, put them on your dog(don't actually put them on your dog). It doesn't matter where you put them because purchasing one of these johnnies is about the coolest thing you could do. -- Love, the EGM Team", false),
(23, "EGM Clear/Pink Slap", "./images/home-imgs/EGM-Long-Logo-Pink-Slap.png", "./images/home-imgs/EGM-Long-Logo-Pink-Slap.png", 5, "Stickers","Put them on your drift car, put them on your show car, put them on your dog(don't actually put them on your dog). It doesn't matter where you put them because purchasing one of these johnnies is about the coolest thing you could do. -- Love, the EGM Team", false),
(24, "EGM 90s Logo Slap", "./images/home-imgs/EGM-Long-Logo-Slap-HKS.png", "./images/home-imgs/EGM-Long-Logo-Slap-HKS.png", 5, "Stickers","Put them on your drift car, put them on your show car, put them on your dog(don't actually put them on your dog). It doesn't matter where you put them because purchasing one of these johnnies is about the coolest thing you could do. -- Love, the EGM Team", false);



SELECT * FROM products;


-- Error Code: 1136. Column count doesn't match value count at row 1